server:
  port: 8080

# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://192.168.101.90:3306/t_gorm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  threads:
    virtual:
      enabled: true
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
